// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCMXR7Qv09e16rv2oX3gnuQ1G-fjwQaUFU',
    appId: '1:841466911259:web:1a8d314416af431d73b6be',
    messagingSenderId: '841466911259',
    projectId: 'blooddonation-b2577',
    authDomain: 'blooddonation-b2577.firebaseapp.com',
    storageBucket: 'blooddonation-b2577.appspot.com',
    measurementId: 'G-0WWZR7TRFZ',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyC56wV1UvOErbRPwrz0muX0bya7ckl93mk',
    appId: '1:841466911259:android:507fcca50224035373b6be',
    messagingSenderId: '841466911259',
    projectId: 'blooddonation-b2577',
    storageBucket: 'blooddonation-b2577.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyA7UKiXfGyYaZ6whK_KYjMWna0s95wuz28',
    appId: '1:841466911259:ios:93019cc1089a35af73b6be',
    messagingSenderId: '841466911259',
    projectId: 'blooddonation-b2577',
    storageBucket: 'blooddonation-b2577.appspot.com',
    iosBundleId: 'com.example.blood',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyA7UKiXfGyYaZ6whK_KYjMWna0s95wuz28',
    appId: '1:841466911259:ios:93019cc1089a35af73b6be',
    messagingSenderId: '841466911259',
    projectId: 'blooddonation-b2577',
    storageBucket: 'blooddonation-b2577.appspot.com',
    iosBundleId: 'com.example.blood',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCMXR7Qv09e16rv2oX3gnuQ1G-fjwQaUFU',
    appId: '1:841466911259:web:342e508e22fff99773b6be',
    messagingSenderId: '841466911259',
    projectId: 'blooddonation-b2577',
    authDomain: 'blooddonation-b2577.firebaseapp.com',
    storageBucket: 'blooddonation-b2577.appspot.com',
    measurementId: 'G-Z33HN8N3RF',
  );
}
